# Generated by Django 5.1.4 on 2024-12-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
